//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class colors
    {
        public int id { get; set; }
        public Nullable<int> code { get; set; }
        public string color_name { get; set; }
        public string image_url { get; set; }
        public int product_id { get; set; }
    
        public virtual products products { get; set; }
    }
}
