//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TranDungShopEntities : DbContext
    {
        public TranDungShopEntities()
            : base("name=TranDungShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> cart { get; set; }
        public virtual DbSet<cart_detail> cart_detail { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<colors> colors { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<product_categories> product_categories { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<slides> slides { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
