//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.cart_detail = new HashSet<cart_detail>();
            this.colors = new HashSet<colors>();
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> price_start { get; set; }
        public Nullable<double> price_sale { get; set; }
        public string summary { get; set; }
        public string description { get; set; }
        public string detail { get; set; }
        public string slug { get; set; }
        public string size { get; set; }
        public Nullable<int> active { get; set; }
        public string image_url { get; set; }
        public int product_category_id { get; set; }
        public Nullable<int> is_hot { get; set; }
        public Nullable<int> is_new { get; set; }
        public Nullable<int> is_sale { get; set; }
        public int is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_detail> cart_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colors> colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual product_categories product_categories { get; set; }
    }
}
